---
- name: Pull docker image of Calculator
  hosts: localmachine
  remote_user: ansible_user
  tasks:
    - name: Copy jar file
      copy:
        src: ./target/calculator-0.0.1-SNAPSHOT.jar
        dest: ~/

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Pull image
      shell: echo ansible | sudo -S docker pull cookiepie7879/calculator
    
    - name: Running container
      shell: export containerid = echo ansible | sudo -S docker run -it -d cookiepie7879/calculator
