---
- name: Deploying jar
  hosts: localmachine
  remote_user: ansible
  tasks:
    - name: Pull docker image of Calculator
      hosts: all
      tasks:
        - name: Pull image
          docker_image:
            name: cookiepie7879/calculator:latest
            source: pull
   

